name: Build and run unit + integration tests with JDK11
on:
  push:
    branches:
      - issues-1775-jdk11
  pull_request:
    branches:
      - issues-1775-jdk11
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Maven settings.xml
        uses: wei/curl@master
        with:
         args: -o settings.xml https://strongbox.github.io/assets/resources/maven/settings.xml

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        java: [ 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build and test with Maven
        run: mvn clean install -Dintegration.tests -s settings.xml
