name: Build and run unit + integration tests with JDK11
on:
  push:
    branches:
      - issues-1775-jdk11
  pull_request:
    branches:
      - issues-1775-jdk11
jobs:
  build-and-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        java: [ 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Maven settings.xml
        uses: wei/curl@master
        with:
          args: -o settings.xml https://strongbox.github.io/assets/resources/maven/settings.xml
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and run unit and integration tests with Maven
        run: mvn -B -U -T 2 --fail-at-end -s settings.xml clean install -Daether.connector.resumeDownloads=false -Dintegration.tests -Dprepare.revision
